buildFooter()
function buildFooter() {
    var boody = document.body
    var footer = document.createElement("footer")
    var flexParent = document.createElement("div")
    flexParent.setAttribute("id", "flexParent")
    var leftWords = document.createElement("div")
    leftWords.setAttribute("id", "leftWords")
    var footerLogo = document.createElement("img")
    footerLogo.setAttribute("class", "footer-logo")
    footerLogo.setAttribute("src", "footer imgs/loggoTest.png")
    footerLogo.setAttribute("alt", "loggoPage")
    var footerText = document.createElement("p")
    var text = ("Our wondrefull resturant <br />")
    footerText.innerHTML = (text)
    leftWords.appendChild(footerLogo)
    leftWords.appendChild(footerText)
    var centerWords = document.createElement("div")
    centerWords.setAttribute("id", "centerWords")
    var centerWordsText = "Weekly offer <br /> pre - order options <br /> Book a table"
    centerWords.innerHTML = (centerWordsText)
    var thirdWords = document.createElement("div")
    thirdWords.setAttribute("id", "thirdWords")
    var thirdWordsText = "Yosry ragheb street <br /> Assuit city <br /> &copy; 2024 all right reserved"
    thirdWords.innerHTML = (thirdWordsText)
    var contactWords = document.createElement("div")
    contactWords.setAttribute("id", "contactWords")
    var contactWordsText = "Get in touch <br /> <span> <img class='phone' src='./footer imgs/Phone.png' alt='' /> <a href='tel'> 010-1010-1010</a></span><br />"
    contactWords.innerHTML = (contactWordsText)
    var facebook = document.createElement("a")
    facebook.setAttribute("href", "#")
    var facebookImg = document.createElement("img")
    facebookImg.setAttribute("src", "./footer imgs/Facebook Circled.png")
    facebookImg.setAttribute("alt", " facebook")
    facebook.appendChild(facebookImg)
    var twitter = document.createElement("a")
    twitter.setAttribute("href", "#")
    var twitterImg = document.createElement("img")
    twitterImg.setAttribute("src", "./footer imgs/Twitter Circled.png")
    twitterImg.setAttribute("alt", " twitter")
    twitter.appendChild(twitterImg)
    var instagram = document.createElement("a")
    instagram.setAttribute("href", "#")
    var instagramImg = document.createElement("img")
    instagramImg.setAttribute("src", "./footer imgs/Instagram Circle.png")
    instagramImg.setAttribute("alt", " instagram")
    instagram.appendChild(instagramImg)
    var linkedin = document.createElement("a")
    linkedin.setAttribute("href", "#")
    var linkedinImg = document.createElement("img")
    linkedinImg.setAttribute("src", "./footer imgs/LinkedIn Circled.png")
    linkedinImg.setAttribute("alt", "linkedin")
    linkedin.appendChild(linkedinImg)
    contactWords.appendChild(facebook)
    contactWords.appendChild(twitter)
    contactWords.appendChild(instagram)
    contactWords.appendChild(linkedin)
    flexParent.appendChild(leftWords)
    flexParent.appendChild(centerWords)
    flexParent.appendChild(thirdWords)
    flexParent.appendChild(contactWords)
    footer.appendChild(flexParent)
    boody.appendChild(footer)
}
buildLoginAndSignUp()
function buildLoginAndSignUp() {
    var LoginAndSignUpContainer = document.getElementById("lloginAndSignUpContainer")
    var login = document.createElement("div")
    login.setAttribute("id", "login")
    login.setAttribute("class", "invisible")
    var signInCloseBtn = document.createElement("div")
    signInCloseBtn.setAttribute("id", "signInCloseBtn")
    signInCloseBtn.setAttribute("class", "closeIcon")
    var icon = document.createElement("i")
    icon.setAttribute("class", "fa-solid fa-xmark")
    signInCloseBtn.appendChild(icon)
    login.appendChild(signInCloseBtn)
    var loginHeader = document.createElement("div")
    loginHeader.setAttribute("id", "loginHeader")
    var h1 = document.createElement("h1")
    var h1Text = document.createTextNode("Welcome Back !")
    h1.appendChild(h1Text)
    var h3 = document.createElement("h3")
    var h3Text = document.createTextNode("Enter your credenital for login")
    h3.appendChild(h3Text)
    loginHeader.appendChild(h1)
    loginHeader.appendChild(h3)
    login.appendChild(loginHeader)
    var loginForm = document.createElement("form")
    loginForm.setAttribute("id", "loginForm")
    loginForm.setAttribute("method", "post")
    loginForm.setAttribute("novalidate", "")
    var loginemail = document.createElement("input")
    loginemail.setAttribute("type", "email")
    loginemail.setAttribute("id", "loginemail")
    loginemail.setAttribute("placeholder", "Enter your email")
    loginemail.setAttribute("required", "")
    var loginpassword = document.createElement("input")
    loginpassword.setAttribute("type", "password")
    loginpassword.setAttribute("id", "loginpassword")
    loginpassword.setAttribute("placeholder", "Password")
    loginpassword.setAttribute("required", "")
    var submit = document.createElement("button")
    submit.setAttribute("id", "submit")
    submit.setAttribute("type", "submit")
    var submitText = document.createTextNode("Login ")
    submit.appendChild(submitText)
    var buttonForSignUp = document.createElement("p")
    buttonForSignUp.setAttribute("id", "buttonForSignUp")
    var buttonForSignUpText = document.createTextNode("If You Don't Have an account ")
    buttonForSignUp.appendChild(buttonForSignUpText)
    var a = document.createElement("a")
    a.setAttribute("onclick", "toggleSignUpForm()")
    a.setAttribute("href", "#")
    var aText = document.createTextNode("signUp")
    a.appendChild(aText)
    buttonForSignUp.appendChild(a)
    var br = document.createElement("br")
    loginForm.appendChild(loginemail)
    loginForm.appendChild(loginpassword)
    loginForm.appendChild(submit)
    loginForm.appendChild(buttonForSignUp)
    loginForm.appendChild(br)
    login.appendChild(loginForm)
    var signUp = document.createElement("div")
    signUp.setAttribute("id", "signUp")
    signUp.setAttribute("class", "invisible")
    var signUpCloseBtn = document.createElement("div")
    signUpCloseBtn.setAttribute("id", "signUpCloseBtn")
    signUpCloseBtn.setAttribute("class", "closeIcon")
    var icon = document.createElement("i")
    icon.setAttribute("class", "fa-solid fa-xmark")
    signUpCloseBtn.appendChild(icon)
    signUp.appendChild(signUpCloseBtn)
    var signUpHeader = document.createElement("div")
    signUpHeader.setAttribute("id", "signUpHeader")
    var h1 = document.createElement("h1")
    var h1Text = document.createTextNode("Sign Up")
    h1.appendChild(h1Text)
    var h3 = document.createElement("h3")
    var h3Text = document.createTextNode("Create your account")
    h3.appendChild(h3Text)
    signUpHeader.appendChild(h1)
    signUpHeader.appendChild(h3)
    signUp.appendChild(signUpHeader)
    var myForm = document.createElement("form")
    myForm.setAttribute("method", "post")
    myForm.setAttribute("id", "myForm")
    myForm.setAttribute("novalidate", "")
    signUp.appendChild(myForm)
    var fName = document.createElement("input")
    fName.setAttribute("type", "text")
    fName.setAttribute("id", "fName")
    fName.setAttribute("placeholder", "First Name")
    fName.setAttribute("required", "")
    var lName = document.createElement("input")
    lName.setAttribute("type", "text")
    lName.setAttribute("id", "lName")
    lName.setAttribute("placeholder", "Last Name")
    lName.setAttribute("required", "")
    var signUpemail = document.createElement("input")
    signUpemail.setAttribute("type", "email")
    signUpemail.setAttribute("id", "signUpemail")
    signUpemail.setAttribute("placeholder", " Email")
    signUpemail.setAttribute("required", "")
    var signUpPassword = document.createElement("input")
    signUpPassword.setAttribute("type", "password")
    signUpPassword.setAttribute("id", "signUpPassword")
    signUpPassword.setAttribute("placeholder", "Password")
    signUpPassword.setAttribute("required", "")
    var submit = document.createElement("button")
    submit.setAttribute("id", "submit")
    submit.setAttribute("type", "submit")
    var submitText = document.createTextNode("Sign Up")
    submit.appendChild(submitText)
    myForm.appendChild(fName)
    myForm.appendChild(lName)
    myForm.appendChild(signUpemail)
    myForm.appendChild(signUpPassword)
    myForm.appendChild(submit)
    var p = document.createElement("p")
    var pText = document.createTextNode("OR")
    p.appendChild(pText)
    signUp.appendChild(p)
    var easySubmit = document.createElement("button")
    easySubmit.setAttribute("id", "easySubmit")
    easySubmit.setAttribute("type", "button")
    var googleIcon = document.createElement("img")
    googleIcon.setAttribute("id", "googleIcon")
    googleIcon.setAttribute("src", "./Sign Up Page/google_icon.png")
    googleIcon.setAttribute("alt", " googleIcon")
    var googleText = document.createTextNode(" Login with Google ")
    easySubmit.appendChild(googleIcon)
    easySubmit.appendChild(googleText)
    signUp.appendChild(easySubmit)
    LoginAndSignUpContainer.appendChild(login)
    LoginAndSignUpContainer.appendChild(signUp)
}
buildsearchPopUpAside()
function buildsearchPopUpAside() {
    var searchPopUpAside = document.getElementById("searchPopUpAside")
    var searchPopUpGrandContainer = document.createElement("div")
    searchPopUpGrandContainer.setAttribute("class", "searchPopUpGrandContainer visibleSearch")
    var searchPopUpBtnContainer = document.createElement("div")
    searchPopUpBtnContainer.setAttribute("class", "searchPopUpBtnContainer")
    var searchPopUpBtn = document.createElement("button")
    searchPopUpBtn.setAttribute("onclick", "closePopUp()")
    searchPopUpBtn.setAttribute("class", "searchPopUpBtn")
    var searchText = document.createTextNode("X")
    searchPopUpBtn.appendChild(searchText)
    searchPopUpBtnContainer.appendChild(searchPopUpBtn)
    searchPopUpGrandContainer.appendChild(searchPopUpBtnContainer)
    var searchPopUpParentWImg = document.createElement("div")
    searchPopUpParentWImg.setAttribute("class", "searchPopUpParentWImg")
    var searchPopUpImg = document.createElement("img")
    searchPopUpImg.setAttribute("class", "searchPopUpImg")
    searchPopUpImg.setAttribute("src", "https://via.placeholder.com/217x231")
    searchPopUpImg.setAttribute("alt", "ItemImg")
    searchPopUpParentWImg.appendChild(searchPopUpImg)
    searchPopUpGrandContainer.appendChild(searchPopUpParentWImg)
    var searchPopUpDesTitlePrice = document.createElement("div")
    searchPopUpDesTitlePrice.setAttribute("class", "searchPopUpDesTitlePrice1")
    var searchPopUpTitle = document.createElement("h2")
    searchPopUpTitle.setAttribute("class", "searchPopUpTitle")
    var searchPopUpTitleText = document.createTextNode("Grilled Salmon with Lemon Dill Sauce")
    searchPopUpTitle.appendChild(searchPopUpTitleText)
    searchPopUpDesTitlePrice.appendChild(searchPopUpTitle)
    var searchPopUpDescription = document.createElement("div")
    searchPopUpDescription.setAttribute("class", "searchPopUpDescription")
    var searchPopUpDescriptionText = document.createTextNode("Freshly grilled salmon fillet topped with a creamy lemon dill sauce, served with asparagus and roasted potatoes.")
    searchPopUpDescription.appendChild(searchPopUpDescriptionText)
    searchPopUpDesTitlePrice.appendChild(searchPopUpDescription)
    var searchPopUpPrice = document.createElement("p")
    searchPopUpPrice.setAttribute("class", "searchPopUpPrice")
    var searchPopUpPriceText = document.createTextNode("$ 10.00")
    searchPopUpPrice.appendChild(searchPopUpPriceText)
    searchPopUpDesTitlePrice.appendChild(searchPopUpPrice)
    searchPopUpParentWImg.appendChild(searchPopUpDesTitlePrice)
    var addCartBtnForSearch = document.createElement("button")
    addCartBtnForSearch.setAttribute("id", "addCartBtnForSearch")
    addCartBtnForSearch.setAttribute("class", "searchPopUpBtn")
    var addCartBtnForSearchText = document.createTextNode(" Add to cart")
    addCartBtnForSearch.appendChild(addCartBtnForSearchText)
    searchPopUpDesTitlePrice.appendChild(addCartBtnForSearch)
    searchPopUpAside.appendChild(searchPopUpGrandContainer)
}

buildCartAside()
function buildCartAside() {
    var cartAside = document.getElementById("cartAside")
    var cart1 = document.createElement("div")
    cart1.setAttribute("id", "cart1")
    cart1.setAttribute("class", "cart ")
    var cartCancelButton = document.createElement("button")
    cartCancelButton.setAttribute("class", "cartCancelButton")
    cartCancelButton.setAttribute("onclick", "removecart() ")
    var cartCancelButtonIcon = document.createElement("i")
    cartCancelButtonIcon.setAttribute("class", "fa-solid fa-xmark")
    cartCancelButton.appendChild(cartCancelButtonIcon)
    cart1.appendChild(cartCancelButton)
    var cartBody = document.createElement("div")
    cartBody.setAttribute("id", "cartBody")
    var cartItemsContainer = document.createElement("div")
    cartItemsContainer.setAttribute("class", "cartItemsContainer")
    cartBody.appendChild(cartItemsContainer)
    cart1.appendChild(cartBody)
    cartAside.appendChild(cart1)
}